#!/usr/bin/env bash
# ============================================================
# UMBP IO bandwidth one-shot runner
#
# What this script does, in order:
#   1. Validate repo state (clean except for a known ignore-list).
#   2. Fetch + checkout the IO-BW test branch via HTTPS (no SSH key needed).
#   3. Kill any stale sglang / UMBP master / SPDK proxy processes that
#      would otherwise hold the GPUs / NVMe / ports.
#   4. Run a small case3 (HBM_DRAM_SSD) benchmark with DUMMY_FORWARD so
#      we can iterate quickly without weight-load overhead.
#   5. Find the latest results dir and call diagnose_iobw_logs.sh on it.
#
# All parameters are env-overridable.  Defaults match the "small-scale"
# case from the test plan (NUM_ROUNDS=20, NUM_CLIENTS=4, MAX_PARALLEL=4,
# REQUEST_RATE=10, HICACHE_SIZE=32, UMBP_SSD_BACKEND=spdk_proxy).
# ============================================================
set -euo pipefail

REPO_DIR="${REPO_DIR:-/sgl-workspace/sglang}"
REPO_URL="${REPO_URL:-https://github.com/zhangfei829/sglang.git}"
REPO_REMOTE_NAME="${REPO_REMOTE_NAME:-iobw}"
BRANCH="${BRANCH:-test/umbp-io-bandwidth-stats}"
EXPECTED_COMMIT="${EXPECTED_COMMIT:-}"

DO_CHECKOUT="${DO_CHECKOUT:-true}"
DO_KILL_STALE="${DO_KILL_STALE:-true}"
DO_RUN_BENCH="${DO_RUN_BENCH:-true}"
DO_DIAGNOSE="${DO_DIAGNOSE:-true}"

# --- Bench parameters (small-scale defaults that already passed) -------
# MODEL_PATH default is the verified skyriver07 model (has config.json, MLA).
# Do NOT use /nfs/data/DeepSeek-V3 -- that path has no config.json on this box.
export MODEL_PATH="${MODEL_PATH:-/mnt/nvme1/data/DeepSeekV3.1}"
export CASES_OVERRIDE="${CASES_OVERRIDE:-case3:HBM_DRAM_SSD}"
export DUMMY_FORWARD="${DUMMY_FORWARD:-true}"
export NUM_ROUNDS="${NUM_ROUNDS:-20}"
export NUM_CLIENTS="${NUM_CLIENTS:-4}"
export MAX_PARALLEL="${MAX_PARALLEL:-4}"
export REQUEST_RATE="${REQUEST_RATE:-10}"
export HICACHE_SIZE="${HICACHE_SIZE:-32}"
# DRAM-only L3 by default (L3 DRAM tier -> L2 host DRAM -> HBM, no SSD/SPDK).
# Set UMBP_SSD_BYTES=0 to disable the SSD tier; keep backend=posix so the bench
# never injects spdk_* config fields. For an SSD run, set UMBP_SSD_BACKEND=spdk_proxy,
# UMBP_SSD_BYTES>0, UMBP_SPDK_NVME_PCI=..., UMBP_SPDK_PROXY_BIN=... explicitly.
export UMBP_SSD_BACKEND="${UMBP_SSD_BACKEND:-posix}"
export UMBP_SSD_BYTES="${UMBP_SSD_BYTES:-0}"

# --- IOBW logging knobs ------------------------------------------------
export UMBP_IO_BW_STATS="${UMBP_IO_BW_STATS:-true}"
export UMBP_IO_BW_STATS_MAX_RECORDS="${UMBP_IO_BW_STATS_MAX_RECORDS:-100000}"
# UMBP_IO_BW_STATS_DIR is intentionally left unset by default so the
# JSONL side-channel lands in <cwd>/umbp_iobw_logs, which the runner
# moves into RESULTS_DIR after the benchmark finishes.
export UMBP_IO_BW_STATS_JSONL="${UMBP_IO_BW_STATS_JSONL:-true}"
export UMBP_IO_BW_STATS_JSONL_FSYNC="${UMBP_IO_BW_STATS_JSONL_FSYNC:-true}"

# --- Helpers ----------------------------------------------------------
log() { echo "[$(date '+%H:%M:%S')] [iobw-runner] $*"; }
die() { log "ERROR: $*"; exit 1; }

# Paths that the runner is allowed to leave dirty without aborting the
# checkout.  Anything generated by previous benchmark runs or the runner
# itself goes here.  Compared against `git status --porcelain` output.
declare -a DIRTY_IGNORE_PATHS=(
    "benchmark/hicache/results/"
    "tools/iobw/run_umbp_iobw_test.sh"
    "tools/iobw/diagnose_iobw_logs.sh"
    "tools/iobw/summarize_iobw_jsonl.py"
    "tools/iobw/README.md"
    "umbp_iobw_logs/"
    "run_umbp_iobw_test.sh"
    "gpucore."
    # ROCm hipify-generated artifacts (untracked on MI300X boxes); never block checkout.
    ".hip"
    "sgl-kernel/include/hip/"
    "utils_hip.h"
    "sgl-kernel/sgl-kernel"
    ".cursor/rules/"
)

is_path_ignored_for_dirty() {
    local p="$1"
    for ignore in "${DIRTY_IGNORE_PATHS[@]}"; do
        # Allow either exact match, prefix match (dir), or filename match.
        if [[ "$p" == "$ignore" || "$p" == "$ignore"* ]]; then
            return 0
        fi
        # Extension-style entry (starts with a dot, e.g. ".hip") -> suffix match.
        if [[ "$ignore" == .* && "$p" == *"$ignore" ]]; then
            return 0
        fi
        local base
        base="$(basename "$ignore")"
        if [[ "$(basename "$p")" == "$base" ]]; then
            return 0
        fi
    done
    return 1
}

ensure_clean_repo() {
    if ! git -C "$REPO_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        die "$REPO_DIR is not a git repo"
    fi

    # Parse porcelain output; tolerate paths in the ignore list.
    local bad=()
    while IFS= read -r line; do
        # line format: "XY path" or "XY orig -> new" for renames.
        local status_field path_field
        status_field="${line:0:2}"
        path_field="${line:3}"
        # Strip rename arrows.
        if [[ "$path_field" == *" -> "* ]]; then
            path_field="${path_field##*-> }"
        fi
        # Quoted paths from `git status -z` would be different; porcelain v1
        # quotes only when needed.  Trim surrounding quotes if any.
        path_field="${path_field%\"}"
        path_field="${path_field#\"}"
        if ! is_path_ignored_for_dirty "$path_field"; then
            bad+=("[$status_field] $path_field")
        fi
    done < <(git -C "$REPO_DIR" status --porcelain)

    if (( ${#bad[@]} > 0 )); then
        log "Repo has uncommitted changes outside the ignore list:"
        printf '  %s\n' "${bad[@]}"
        log "Refusing to checkout.  Either commit/stash them or extend"
        log "DIRTY_IGNORE_PATHS in $0."
        return 1
    fi
    return 0
}

checkout_branch() {
    log "Configuring remote ${REPO_REMOTE_NAME} -> ${REPO_URL}"
    if git -C "$REPO_DIR" remote get-url "$REPO_REMOTE_NAME" >/dev/null 2>&1; then
        git -C "$REPO_DIR" remote set-url "$REPO_REMOTE_NAME" "$REPO_URL"
    else
        git -C "$REPO_DIR" remote add "$REPO_REMOTE_NAME" "$REPO_URL"
    fi

    log "Fetching ${REPO_REMOTE_NAME}/${BRANCH} ..."
    git -C "$REPO_DIR" fetch --prune "$REPO_REMOTE_NAME" "$BRANCH"

    local target_ref="${REPO_REMOTE_NAME}/${BRANCH}"
    log "Checking out ${target_ref}"
    git -C "$REPO_DIR" checkout -B "$BRANCH" "$target_ref"

    local head
    head=$(git -C "$REPO_DIR" rev-parse --short HEAD)
    log "HEAD is now ${head}"

    if [[ -n "$EXPECTED_COMMIT" && "$head" != "$EXPECTED_COMMIT"* ]]; then
        die "HEAD ${head} does not match EXPECTED_COMMIT=${EXPECTED_COMMIT}"
    fi

    # Sanity-check the IOBW markers actually exist in the source.
    if ! grep -q "bandwidth_gib_s" \
            "$REPO_DIR/python/sglang/srt/mem_cache/storage/umbp/umbp_store.py"; then
        die "umbp_store.py at HEAD does not contain 'bandwidth_gib_s' marker"
    fi
    if ! grep -q "\\[UMBPStore\\]\\[IOBW\\]" \
            "$REPO_DIR/python/sglang/srt/mem_cache/storage/umbp/umbp_store.py"; then
        die "umbp_store.py at HEAD does not contain '[UMBPStore][IOBW]' marker"
    fi
    log "Source markers present: bandwidth_gib_s + [UMBPStore][IOBW]"
}

kill_stale() {
    log "Killing stale launch_server / umbp_master / spdk_proxy processes ..."
    pkill -f "sglang\.launch_server|sglang\.srt\.|sglang serve|launch_server\.py" 2>/dev/null || true
    pkill -f "umbp_master" 2>/dev/null || true
    pkill -f "spdk_proxy" 2>/dev/null || true
    sleep 2
    # Anything still up?
    local leftover
    leftover=$(pgrep -af "sglang\.launch_server|launch_server\.py|umbp_master|spdk_proxy" || true)
    if [[ -n "$leftover" ]]; then
        log "WARNING: some processes survived SIGTERM, sending SIGKILL:"
        echo "$leftover" | sed 's/^/    /'
        pkill -9 -f "sglang\.launch_server|sglang\.srt\.|sglang serve|launch_server\.py" 2>/dev/null || true
        pkill -9 -f "umbp_master" 2>/dev/null || true
        pkill -9 -f "spdk_proxy" 2>/dev/null || true
        sleep 2
    fi
    leftover=$(pgrep -af "sglang\.launch_server|launch_server\.py|umbp_master|spdk_proxy" || true)
    if [[ -n "$leftover" ]]; then
        log "ERROR: still running after SIGKILL:"
        echo "$leftover" | sed 's/^/    /'
        return 1
    fi
    log "All stale processes are gone."
}

run_bench() {
    local script="$REPO_DIR/benchmark/hicache/run_tiered_cache_bench_dp8ep8.sh"
    [[ -x "$script" ]] || chmod +x "$script"

    log "Running benchmark: $script"
    log "  CASES_OVERRIDE  = $CASES_OVERRIDE"
    log "  NUM_ROUNDS      = $NUM_ROUNDS"
    log "  NUM_CLIENTS     = $NUM_CLIENTS"
    log "  MAX_PARALLEL    = $MAX_PARALLEL"
    log "  REQUEST_RATE    = $REQUEST_RATE"
    log "  HICACHE_SIZE    = $HICACHE_SIZE"
    log "  UMBP_SSD_BACKEND= $UMBP_SSD_BACKEND"
    log "  UMBP_SSD_BYTES  = ${UMBP_SSD_BYTES:-}"
    log "  UMBP_SPDK_NVME  = ${UMBP_SPDK_NVME_PCI:-}"
    log "  DUMMY_FORWARD   = $DUMMY_FORWARD"

    pushd "$REPO_DIR" >/dev/null
    set +e
    "$script"
    local rc=$?
    set -e
    popd >/dev/null
    log "Benchmark script exited with code $rc"
    return $rc
}

latest_results_dir() {
    local base="$REPO_DIR/benchmark/hicache/results/tiered_cache_bench_dp8ep8"
    [[ -d "$base" ]] || return 1
    ls -1dt "$base"/*/ 2>/dev/null | head -n 1 | sed 's:/$::'
}

collect_side_channel_logs() {
    local rdir="$1"
    [[ -n "$rdir" && -d "$rdir" ]] || return 0

    local moved=0
    if [[ -d "$REPO_DIR/umbp_iobw_logs" ]]; then
        local dst="$rdir/umbp_iobw_logs"
        mkdir -p "$dst"
        if mv "$REPO_DIR/umbp_iobw_logs"/* "$dst"/ 2>/dev/null; then
            moved=1
            log "Moved JSONL side-channel files from cwd into $dst"
        fi
        rmdir "$REPO_DIR/umbp_iobw_logs" 2>/dev/null || true
    fi

    if (( moved == 0 )); then
        # Look in cwd of the *parent* (where the script was launched from)
        # in case PWD changed.  Best-effort only.
        if [[ -d "$PWD/umbp_iobw_logs" && "$PWD" != "$REPO_DIR" ]]; then
            local dst="$rdir/umbp_iobw_logs"
            mkdir -p "$dst"
            mv "$PWD/umbp_iobw_logs"/* "$dst"/ 2>/dev/null || true
            rmdir "$PWD/umbp_iobw_logs" 2>/dev/null || true
            log "Moved JSONL side-channel files from $PWD into $dst"
        fi
    fi
}

run_diagnose() {
    local rdir="$1"
    local diag="$REPO_DIR/tools/iobw/diagnose_iobw_logs.sh"
    if [[ ! -x "$diag" ]]; then
        chmod +x "$diag" 2>/dev/null || true
    fi
    if [[ -x "$diag" ]]; then
        "$diag" "$rdir"
    else
        log "WARNING: $diag is missing; skipping diagnose step."
    fi
}

# ---- Main -------------------------------------------------------------
log "Repo: $REPO_DIR"
log "Remote: $REPO_REMOTE_NAME -> $REPO_URL"
log "Branch: $BRANCH"

if [[ "$DO_CHECKOUT" == "true" ]]; then
    ensure_clean_repo || die "repo not clean; aborting"
    checkout_branch
else
    log "DO_CHECKOUT=false → skipping checkout step"
fi

if [[ "$DO_KILL_STALE" == "true" ]]; then
    kill_stale || die "failed to kill stale processes"
else
    log "DO_KILL_STALE=false → skipping process cleanup"
fi

BENCH_RC=0
if [[ "$DO_RUN_BENCH" == "true" ]]; then
    run_bench || BENCH_RC=$?
else
    log "DO_RUN_BENCH=false → skipping benchmark"
fi

RDIR="$(latest_results_dir || true)"
if [[ -n "$RDIR" ]]; then
    log "Latest results dir: $RDIR"
    collect_side_channel_logs "$RDIR"
else
    log "WARNING: could not locate a results dir under benchmark/hicache/results/tiered_cache_bench_dp8ep8/"
fi

if [[ "$DO_DIAGNOSE" == "true" && -n "$RDIR" ]]; then
    run_diagnose "$RDIR"
fi

log "Done.  Benchmark exit code: $BENCH_RC"
exit "$BENCH_RC"
